### PR TITLE
Compatibility with newer versions available here! (>= 2021.1)

### LINKED ISSUE #10: Plugin is incompatible with PhpStorm 2021.1 EAP
I know, it's a EAP, but… all other plugins I use do work with it. 😬

### LINKED ISSUE #14: Plugin is incompatible with Idea 2021.2
Please update ;)

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Please note that I also updated the Copyright years and removed the `com.github.ManifestClasspath` plugin as it breaks the build on Windows actually (I built the plugin successfully on Windows myself)

Edit: Versions can be found here: https://plugins.jetbrains.com/plugin/18612-diff--patch-file-support

Fixes #10 
Fixes #14

### CODE REVIEW

**Review by Spurlos — APPROVED** [review]

**Comment by larvanitis** [comment]
I just installed `intellij-diff-plugin-2.1.7-2021.2-SNAPSHOT.jar` to IDEA 2021.1.2 _IU-211.7442.40_ and so far so good.

**Comment by ThexXTURBOXx** [comment]
@larvanitis The 2021.2 EAP version worked on 2021.1.2 for you? That's very nice to hear. Maybe, we don't even need the other version after all

**Comment by this** [comment]
Latest `intellij-diff-plugin-2.1.7-2021.2-SNAPSHOT.jar` works with PyCharm 2021.3.1 (Professional Edition).

**Comment by denisvmedia** [comment]
@ThexXTURBOXx thanks for your efforts. Do you think, it's possible to publish your builds in the official JetBrains marketplace?

**Comment by ThexXTURBOXx** [comment]
@denisvmedia I also already thought about that since the original author seems to have abandoned this project.
Also, because I am not very familiar with licenses and what they mean, I read up some articles about what I may do with this plugin.
Appearently, I am permitted to distribute my builds as long as I include the original copyright notice and state what I changed in the code.
So, this is exactly what I will do.

I will keep you updated on my progress on uploading the plugin :)

**Comment by ThexXTURBOXx** [comment]
Uploaded the first version here: https://plugins.jetbrains.com/plugin/18612-diff--patch-file-support

According to JetBrains, the approval process will take two business days. So, I will keep you updated on when the plugin will be available on the Marketplace :)

**Comment by ThexXTURBOXx** [comment]
The plugin has successfully been approved by JetBrains!
You can now install it from within your IDE directly :)

**Comment by VergeDX** [comment]
Thanks what you've done!

**Comment by ThomasR** [comment]
Thank you @ThexXTURBOXx for contributing! This is awesome! 🤗 

I haven't been active on Github recently, so I will archive my repo and leave the project in your hands.

One final note on the copyright:
Please respect the [license terms](https://www.apache.org/licenses/LICENSE-2.0), specifically section _4. Redistribution_

- The year in my copyright notice should not be changed
- If you modify a file, you must add a note that you have done so.
- (Feel free to add your own copyright to any files added by you, as long as it's compatible with Apache-2.0)

**Comment by ThexXTURBOXx** [comment]
Dear Thomas, thank you very much for your response! :)
Indeed, you are right. I was a newbie when it comes to licensing when I started this fork. I will change these back ASAP!
I will also follow the rest of what is mentioned within the Apache-2.0 license in the future, thank you for the reminder!

**Pull request closed without merging**
